### ISSUE TITLE
stri_replace_all_fixed works iteratively (as intended?)

### ISSUE THREAD

**Issue by jakob-r** [gagolews/stringi#349]
Consider the following example:
```r
stringi::stri_replace_all_fixed(c("A", "B", "A"), c("A", "B"), c("B", "C"), vectorize_all = FALSE)
```
The output is:
```
[1] "C" "C" "C"
```

Instead I would expect
```
[1] "B" "C" "B"
```

Is this intended or a bug?

**Comment by gagolews** [comment]
Nah, this behavior is documented in the package manual:

> [...]this is equivalent to     something like ‘for (i in 1:npatterns) str <-     stri_replace_all(str, pattern[i], replacement[i]’. [...]

Recently a similar issue was raised regarding `stri_trans_char` and overlapping maps, see #343

so in your example, you'd have:

```
> stringi::stri_trans_char(c("A", "B", "A"), "AB", "BC")
[1] "B" "C" "B"
```

Replacing a similar behavior in case of stri_replace_all could be error-prone, I think, because the patterns might be of different lengths and the matches to patterns might overlap -- what then?
